print('*** Receta de Cocina ***')
nombre_receta = input('Ingresa el nombre de la receta: ')
ingredientes_receta = input('Ingresa los ingredientes de la recetas: ')
tiempo_preparacion_receta = int(input('Ingresa el tiempo de preparacion (min): '))
nivel_dificultad = input('Ingresa el nivel de dificultad (Facil, Medio o dicifil): ')
print('-------------------------')
print(f'Nombre receta: {nombre_receta}')
print(f'Ingredientes: {ingredientes_receta}')
print(f'Tiempo de preparacion (min): {tiempo_preparacion_receta}')
print(f'Dificultad: {nivel_dificultad}')